# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5944ff34bcafe1791d1a33b5d7ff218aa8188641a2473ca4e1a4bdacf07f09f91d0f6007bdd56ea5bbe834d123a17c396ec188776dc19ead1c092b790010d0d0

test:
  secret_key_base: d452b77f913f63ce05ccce1c201de847b45101c468ae30b125abe16a4e4d5ffc951412675f5dbc431dfcee4e88556703db3a66905022e14a1bd1c35832758e02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
